[workspace]
members = ["bignat"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
num-bigint = "0.5.1"

[package]
name = "lean-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib", "staticlib"]

[features]
test-ffi = []

[dependencies]
bignat = { path = "bignat" }
num-bigint.workspace = true

[build-dependencies]
bindgen = "0.72"
cc = "1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"